name: 'vscode'
description: 'run vscode with directory'
inputs:
  repo:
    description: repo
  branch:
    description: branch
  goto:
    description: open file
    default: ''
  uri:
    description: uri to open with vscode
  command:
    description: code or code-insiders
    default: code

outputs:
  status:
    description: result

runs:
  using: node12
  main: dist/index.js
