name: 'vscode'
description: 'run vscode with directory'
inputs:
  path:
    description: path
  remote:
    description: vscode's "--remote" option
  folderUri:
    description: vscode's "--folder-uri" option
  command:
    description: code or code-insiders or arc
    default: code

outputs:
  status:
    description: result

runs:
  using: node16
  main: dist/index.js
