name: 'status'
description: 'update vspn status'
inputs:
  requestId:
    description: request id
    required: true
  status:
    description: status to update
    required: true

runs:
  using: "composite"
  steps: 
    - name: status started
      run: |
        curl -d '{"requestId": "${{ inputs.requestId }}", "status": "${{ inputs.status }}"}' \
            -H "Content-Type: application/json" \
            -X POST https://vspn.chitacan.io/api/status
      shell: bash
