name: run vscode on cmba
on:
  workflow_dispatch:
    inputs:
      requestId:
        description: request id
        required: true
      path:
        description: path
      remote:
        description: vscode's "--remote" option
      folderUri:
        description: vscode's "--folder-uri" option

jobs:
  run_vscode:
    runs-on: [self-hosted, cmba]
    steps:
      - name: open vscode
        id: open_vscode
        uses: chitacan/vspn/actions/vscode@master
        with:
          path: ${{ github.event.inputs.path }}
          remote: ${{ github.event.inputs.remote }}
          folderUri: ${{ github.event.inputs.folderUri }}
        env:
          RUNNER_TRACKING_ID: ""
